sudo: required
services:
  - docker
before_install:
  - docker build -t ddhairya/frontend -f Dockerfile.dev .
branches:
  only:
    - dhairya-dev
script:
  - docker run ddhairya/frontend npn run test -- --coverage