apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    component: web
spec:
  containers:
    - name: frontend
      image: ddhairya/frontend
      ports:
        - containerPort: 3000
