# sudo: required
# services:
#   - docker
# before_install:
#   - docker build -t ddhairya/frontend -f frontend/Dockerfile.dev .
# branches:
#   only:
#     - dhairya-dev
# script:
#   - docker run ddhairya/frontend npn run test -- --coverage


#----------- travis is no more free so this is the sample file not in action ----------
sudo: required
service:
  - docker

before-install:
  - docker build -t ddhairya/frontend -f ./frontend/frontend.Dockerfile.dev ./frontend
  # can have other build commad for the test

script:
  - docker run ddhairya/frontend npn test -- --coverage
  # can run the builds with test command

after-success:
  - docker build -t ddhairya/microservice-frontend ./frontend
  - docker build -t ddhairya/microservice-ngnix ./ngnix
  - docker build -t ddhairya.microservice-backend ./backend
  #LOGIN to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the docker images to Docker Hub
  - docker push ddhairya/microservice-frontend
  - docker push ddhairya/microservice-ngnix
  - docker push ddhairya/microservice-backend

branches:
  only:
    -dhairya-dev

depoly:
  provider: elasticbeanstalk
  region: 'eu-northt-1'
  app: aws-application-name
  env: aws-application-env
  bucket_name: elastic-s3-bucket-name
  bucket_path: give-bucket-name
  on:
    branch: dhairya-dev
  access_key_id: $AWS_ACCESS_KEY_VAR_NAME_TRAVISCI
  secret_access_key:
    secure: $AWS_SECRET_KEY_VAR_NAME_TRAVISCI

